#!/bin/sh

sxhkd &
picom &
feh --bg-fill --randomize ~/wallpapers/
bspc monitor -d 1 2 3 

bspc config focused_border_color "#009688"
bspc config normal_border_color "#2A373E"
bspc config border_width 2
bspc config window_gap 0

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
